# Generated by Django 5.1.15 on 2026-08-17 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Group name, e.g., G1, F', max_length=20)),
            ],
            options={
                'ordering': ['section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(help_text='Room identifier, e.g., C-301, Lab-2', max_length=30, unique=True)),
                ('building', models.CharField(default='Engineering Block C', max_length=100)),
                ('floor', models.IntegerField(default=3)),
                ('room_type', models.CharField(choices=[('LECTURE_HALL', 'Lecture Hall'), ('LAB', 'Lab'), ('TUTORIAL_ROOM', 'Tutorial Room'), ('AUDITORIUM', 'Auditorium')], default='LECTURE_HALL', max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Seating/lab station capacity')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Section name, e.g., CSE-A', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=60, help_text='Maximum student capacity in this section')),
            ],
            options={
                'ordering': ['semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(help_text='Unique faculty employee ID', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(default='Assistant Professor', help_text='e.g. Assistant Professor, Associate Professor, Professor', max_length=50)),
                ('department', models.CharField(default='CSE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='MergeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Descriptive name for merged group, e.g., CSE-F+H+J', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional notes or reasoning for merged group schedule')),
                ('groups', models.ManyToManyField(help_text='Component groups included in this merged group', related_name='merge_groups', to='timetable.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='timetable.section'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(help_text='Semester number, e.g., 1 to 8')),
                ('academic_year', models.CharField(help_text='Academic session year, e.g., 2025-2026', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this semester is currently active')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('number', 'academic_year'), name='unique_semester_number_academic_year')],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='timetable.semester'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Subject code, e.g., CS101, CS502', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full subject title', max_length=150)),
                ('short_name', models.CharField(help_text='Short code/acronym, e.g., DBMS', max_length=30)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('TUTORIAL', 'Tutorial'), ('ELECTIVE', 'Elective')], default='THEORY', max_length=20)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='timetable.semester')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('period', models.PositiveSmallIntegerField(help_text='Period index, e.g., 1 to 8')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['day', 'period'],
                'constraints': [models.UniqueConstraint(fields=('day', 'period'), name='unique_timeslot_day_period')],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('period', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab'), ('TUTORIAL', 'Tutorial')], default='LECTURE', max_length=20)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetable.group')),
                ('merge_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetable.mergegroup')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.room')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.timeslot')),
            ],
            options={
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['day', 'period', 'room'],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'section'), name='unique_group_name_per_section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'semester'), name='unique_section_name_per_semester'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['room', 'day', 'period'], name='idx_tt_room_day_period'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['section', 'day', 'period'], name='idx_tt_sec_day_period'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher', 'day', 'period'], name='idx_tt_teach_day_period'),
        ),
    ]
