# Generated by Django 5.1.15 on 2026-08-21 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_academicholiday_timetableoverride_classcancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of room exception')),
                ('start_time', models.TimeField(blank=True, help_text='Optional start time, null implies full day', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Optional end time, null implies full day', null=True)),
                ('reason', models.CharField(max_length=255)),
                ('exception_type', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('TEMPORARY_CLOSURE', 'Temporary Closure')], default='MAINTENANCE', max_length=30)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='timetable.room')),
            ],
            options={
                'verbose_name_plural': 'Room Exceptions',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Reservation date')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_name', models.CharField(max_length=150)),
                ('reservation_type', models.CharField(choices=[('SEMINAR', 'Seminar'), ('EXAMINATION', 'Examination'), ('DEPARTMENTAL_EVENT', 'Departmental Event'), ('SPECIAL_LECTURE', 'Special Lecture')], default='SPECIAL_LECTURE', max_length=30)),
                ('reserved_by', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='timetable.room')),
            ],
            options={
                'verbose_name_plural': 'Room Reservations',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
